# =============================================================================
# HumanoidHand Environment Configuration (Mujoco + Arctic Assets)
# =============================================================================
# Version: 1.0
# Last Updated: 2025-07-21

env:
  env_name: "humanoid_hand_env"
  numEnvs: 2048
  envSpacing: 1.25
  episodeLength: 200
  frame_skip: 4
  timestep: 0.002
  controlFrequencyInv: 1

  enableDebugVis: false
  enableCameraSensors: false
  cameraDebug: false
  pointCloudDebug: false
  aggregateMode: 1

  objectType: "cube"
  observationType: "full_state"
  asymmetric_observations: true
  handAgentIndex: "[[0, 1, 2, 3, 4, 5]]"
  used_training_objects: ["cube", "egg"]
  used_hand_type: ["shadow"]
  traj_index: ["01_01"]

  useRelativeControl: false
  stiffnessScale: 1.0
  forceLimitScale: 1.0
  dofSpeedScale: 100.0
  actionsMovingAverage: 1.0

  startPositionNoise: 0.0
  startRotationNoise: 0.0
  resetPositionNoise: 0.0
  resetRotationNoise: 0.0
  resetDofPosRandomInterval: 0.0
  resetDofVelRandomInterval: 0.0

  distRewardScale: 50.0
  rotRewardScale: 1.0
  rotEps: 0.1
  actionPenaltyScale: -0.01
  reachGoalBonus: 250.0
  fallDistance: 0.4
  fallPenalty: 0.0
  successTolerance: 0.1
  printNumSuccesses: false
  maxConsecutiveSuccesses: 0

  use_fingertip_reward: false
  use_fingertip_ik: false
  use_joint_space_ik: false
  use_hierarchy: false
  use_p_c_impro_loop: false

asset:
  assetRoot: "assets"

  hands:
    type: "shadow"
    hand_urdf: "assets/hands/g1.xml"
    folder: "hands/shadow_hand"

  objects:
    urdf_dir: "objects/objects"
    mesh_metadata: "objects/object_meta.json"
    converter_script: "objects/obj2urdf.py"
    templates: "objects/subject_vtemplates"
    downsampler: "objects/downsamplers.npy"
    mano_decimator: "objects/mano_decimator_195.npy"
    misc_file: "objects/misc.json"

  scenes:
    table_scene: "scenes/table.xml"
    complete_scene: "scenes/complete_scene.xml"

  textures:
    metal: "textures/metal.png"
    wood: "textures/wood.png"
    skin: "textures/skin.png"

  reports:
    conversion_report: "hands/conversion_report.txt"

task:
  randomize: true
  randomization_params:
    frequency: 600

    observations:
      range: [0.0, 0.002]
      range_correlated: [0.0, 0.001]
      operation: "additive"
      distribution: "gaussian"
      schedule: "linear"
      schedule_steps: 40000

    actions:
      range: [0.0, 0.05]
      range_correlated: [0.0, 0.015]
      operation: "additive"
      distribution: "gaussian"
      schedule: "linear"
      schedule_steps: 40000

    sim_params:
      gravity:
        range: [0.0, 0.4]
        operation: "additive"
        distribution: "gaussian"
        schedule: "linear"
        schedule_steps: 40000

    actor_params:
      hand:
        color: true
        tendon_properties:
          damping:
            range: [0.3, 3.0]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"
            schedule_steps: 30000
          stiffness:
            range: [0.75, 1.5]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"
            schedule_steps: 30000

        dof_properties:
          damping:
            range: [0.3, 3.0]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"
            schedule_steps: 30000
          stiffness:
            range: [0.75, 1.5]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"
            schedule_steps: 30000
          lower:
            range: [0.0, 0.01]
            operation: "additive"
            distribution: "gaussian"
            schedule: "linear"
            schedule_steps: 30000
          upper:
            range: [0.0, 0.01]
            operation: "additive"
            distribution: "gaussian"
            schedule: "linear"
            schedule_steps: 30000

        rigid_body_properties:
          mass:
            range: [0.5, 1.5]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"
            schedule_steps: 30000

        rigid_shape_properties:
          friction:
            num_buckets: 250
            range: [0.7, 1.3]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"
            schedule_steps: 30000

      object:
        scale:
          range: [0.95, 1.05]
          operation: "scaling"
          distribution: "uniform"
          schedule: "linear"
          schedule_steps: 30000

        rigid_body_properties:
          mass:
            range: [0.5, 1.5]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"
            schedule_steps: 30000

        rigid_shape_properties:
          friction:
            num_buckets: 250
            range: [0.7, 1.3]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"
            schedule_steps: 30000

sim:
  substeps: 2
  physx:
    num_threads: 16
    solver_type: 1
    num_position_iterations: 8
    num_velocity_iterations: 0
    contact_offset: 0.02
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 10000.0
    default_buffer_size_multiplier: 5.0
    contact_collection: 1

  flex:
    num_outer_iterations: 5
    num_inner_iterations: 20
    warm_start: 0.8
    relaxation: 0.75
